<h1>Limpiar datos de la convocatoria</h1>
<br /><br />

<h2 style="color: red;">¡Advertencia! Eliminar los datos completamente implica que todos los aspirantes previamente registrados serán eliminados incluyendo sus documentos subidos. No es posible recuperar ninguna información una vez eliminada.<br /><br /> ¿Realmente quiere eliminar toda la información?</h2>
<br /><br />

<a href="<?php echo __BASEURL__;?>/backend/convocatoria/" class="boton">No, regresar</a>
<a href="<?php echo __BASEURL__;?>/backend/convocatoria/limpiardatos/?confirmar=1"  class="boton">Si, Continuar y eliminar todo</a>

<br /><br />
