<?php $db = DB::getInstance(); ?>

<h1>Nuevo documento para la convocatoria</h1>

<form action="<?php echo __BASEURL__; ?>/backend/convocatoria/submitnuevo/" method="post" id="formdocumento">
	<table>
		<tr><td>Nombre documento: </td><td><input type="text" name="documento" class="required" /></td></tr>
		<tr><td>Peso máximo en KB: </td><td><input type="text" name="pesoMax" class="required digits" value="2048" /> (1 MB = 1024 KB)</td></tr>
		<tr><td>Formatos permitidos: </td><td>
			<?php foreach($db->fetchArray("SELECT * FROM `tblformato`") as $f): ?>
			<label><input type="checkbox" name="formatos[]" value="<?php echo $f['idFormato']; ?>" /> <?php echo $f['formato']; ?></label>
			<?php endforeach; ?>
		</td></tr>
		<tr><td>Requisitos del documento: </td><td><textarea name="requisitos" class="requisitos"></textarea></td></tr>

		<tr><td colspan="2"><input type="submit" value="Guardar" /></td></tr>
	</table>
</form>

<br /><br />

<a href="<?php echo __BASEURL__; ?>/backend/convocatoria/" class="boton">&lt; Cancelar</a>



<script type="text/javascript">
$(function(){
	$("#formdocumento").validate();
	
	tinymce.init({
		selector: "textarea.requisitos",
		plugins: ["table"]
	});

});

</script>