version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_DATABASE:
      - MYSQL_USER:
      - MYSQL_PASSWORD:
      - MYSQL_ROOT_PASSWORD:
    volumes:
      -
    ports:
      -3306:3306
    expose:
      - 3306
  
  apache:
    build: 
      context: ./dockerfile
      dockerfile: apache_file
    container_name: apache_container
    restart: always
    volumes:
      -./www:/var/www/html
    expose:
      - 80
    ports:
      - 80:80 