<html>
<head>
	<style type="text/css">
		body{
			font-family: Tahoma, sans-serif;
			font-size: 12px;
		}
	</style>
</head>
<body>
	<p><img src="<?php echo __BASEURL__ ?>/images/logo.jpg"></p>
		<h2 style="text-align: center;"><br />
		Facultad de Química<br />
		Universidad Autónoma de Querétaro</h2>
				
		
	
	<h1>Expediente aprobado</h1>
	<p><strong><?php echo $data['nombre']; ?> :</strong></p>
	<p>Le informamos que su expediente ha sido aprobado en su totalidad en la  fecha: <strong><?php echo $data['fecha']; ?></strong>.</p>
	<br /><br />
	
	
	<?php echo DB::getInstance()->fetchOne('SELECT `infoFinalizado` FROM `tblconvocatoria` WHERE `status` = 1'); ?>
		
		<br /><br /><br />
		<p style="font-size: 11px">Informes: Coordinación del posgrado<br />
		Centro Universitario, Cerro de las Campanas S/N C.P. 76010 Querétaro, Qro.<br />
		Tel. 01 (442) 1921200<br />
		Página web: https://quimica.uaq.mx/<br />
		Correo:</p>

</body>
</html>