<html>
<head>
	<style type="text/css">
		body{
			font-family: Tahoma, sans-serif;
			font-size: 12px;
		}
	</style>
</head>
	<body>
		<p><img src="<?php echo __BASEURL__ ?>/images/logo.jpg"></p>
		
		
		<h2>Recuperar la contraseña de acceso al sistema</h2>
		<p>Se ha generado un nuevo PIN de acceso al sistema para su usuario:</p>
		
		<p><strong><?php echo $data['nombre']; ?></strong></p>
		<br /><p><strong>Usuario: <?php echo $data['email']; ?><br />
		PIN de acceso: <?php echo $data['password']; ?></strong></p>
		<p>URL de acceso: <a href="<?php echo __BASEURL__ ?>"><?php echo __BASEURL__ ?></a></p>
		<br /><br />
		
		<br /><br /><br />
		<p style="font-size: 11px">Informes: Coordinación de la Maestría en Ciencias Sociales<br />
		Centro Universitario, Cerro de las Campanas S/N C.P. 76010 Querétaro, Qro.<br />
		Tel. 01 (442) 1921200 Ext. 5453 y 5471<br />
		Página web: http://fcps.uaq.mx/posgrados/maestria_ciencias_sociales/<br />
		Correo: maestria.sociales@uaq.mx</p>


	</body>
</html>