	<div id="login">
	<div style="width: 400px; margin: 0 auto;">
		<h2>Iniciar sesión:</h2>
		<form id="formLogin" method="post" action="<?php echo __BASEURL__ ?>/backend/login/login/">
		<?php if($this->exists('incorrect')): ?>
			<h2><label class="error">Correo electrónico o contraseña incorrectos.</label></h2>
		<?php endif; ?>
		
		<table>
			<tr><td>Correo electrónico: </td><td><input type="text" name="email"/></td></tr>
			<tr><td>Contraseña: </td><td><input type="password" name="password"/></td></tr>
			<tr><td></td><td><input type="submit" value="Ingresar"/></td></tr>

		</table>
		</form>
	</div>
	<div class="clear"></div>
</div>