<html>
<head>
	<style type="text/css">
		body{
			font-family: Tahoma, sans-serif;
			font-size: 12px;
		}
	</style>
</head>
<body>
	<!--<p style="text-align: right;"><img src="<?php echo __BASEURL__ ?>/images/logo.jpg"></p>-->
	<h1>Expediente completado en espera de revisión</h1>
	<p>Le informamos que el aspirante: <strong><?php echo $data['nombre']; ?></strong>, aspirante a <?php echo '<strong>'.strtoupper(str_replace('_',' ',$data['posg'])).'</strong>';?> <br />
	ha concluido de subir los documentos de su expediente en la fecha: <strong><?php echo $data['fecha']; ?></strong>, y está en espera de ser revisado.</p>
	
	<p>Sistema de expedientes en línea<br />
	Facultad de Química</p>
</body>
</html>