<h2>Propuesta de investigación</h2>
<p>La propuesta de investigación deberá contener:</p>

<p>Título de la investigación</p>

<p>Justificación<br />
Marco Teórico<br />
Hipótesis<br />
Metodología</p>

<p>(Extensión entre 6 y 10 cuartillas)</p>

<h3>Líneas de Investigación</h3>

<ol style="list-style: decimal; margin-left: 25px;">
	<li>Desigualdad, Territorio Y Actores Sociales</li>
	<li>Desarrollo Histórico, Socioeconómico Y Procesos Regionales</li>
	<li>Teoría Y Estudios De La Modernidad Y De Los Procesos De Modernización</li>
	<li>Cambio Político Y Democracia</li>
	<li>Instituciones Políticas Y Comportamiento Electoral</li>
	<li>Movimientos Sociales Y Redes Sociales</li>
	<li>Comunicación Política</li>
	<li>Violencia Social Y Política</li>
	<li>Análisis Económico De La Corrupción</li>
	<li>Racionalidad, Preferencias Y Normas Sociales</li>
	<li>Actitudes Hacia La Democracia, las Instituciones de Justicia y el Estado de Derecho en México.</li>
	<li>Sociedad, Territorio Y Cultura</li>
	<li>Estudios De Género</li>
</ol>