<h2>Fotografía</h2>
<p>Las características de la fotografía son: </p>
<ul style="list-style: disc; margin-left: 25px;">
	<li>Tamaño infantil.</li>
	<li>Reciente. </li>
	<li>Fondo blanco. </li>
	<li>De frente con el rostro descubierto. </li>
	<li>Sin lentes, mascadas, gorras, etc. </li>
	<li>NO deben ser recortadas de otras fotografías. </li>
</ul>
<br /><br />

<p>Si la fotografía se obtuvo con una cámara digital, se deberá ajustar la imagen al tamaño y resolución que se especifica en la tabla anexa. <br />
Si se obtuvo de un scanner se deberán digitalizar en color de 8 bits. a una resolución de 300 puntos por pulgada (ppp o dpi) cumpliendo con las características especificadas en la tabla anexa. <br />
Se deberá recortar la imagen evitando guardar un documento con bordes adicionales. </p>

<table class="listado" style="width: 500px;">
<tr><th>Dimensiones</th><th>Características técnicas</th></tr>
<tr><td>
2.5 x 3 centímetros <br />
ó <br />
1 x 1.2 pulgadas </td>

<td>
<ul style="list-style: disc; margin-left: 25px;">
	<li>Resolución: 300 ppp o dpi </li>
	<li>Color de 8 bits </li>
	<li>Tamaño de imagen: 300 x 360 píxeles </li>
	<li>Formato jpg (compresión media) </li>
	<li>Tamaño de archivo: 40 kb (Aproximado) </li>
</ul>
</td></tr>
</table>
