<h2>Carta de exposición de motivos</h2>

<p>
Extensión: 3 a 5 cuartillas<p>
<p>Contenido: </p>
<ul style="list-style: disc; margin-left: 25px;">
<li>Explicar sus motivos para ingresar al programa</li>
<li>Temas de interés para investigar</li>
<li>Expectativas de la maestría</li>
<li>Experiencia en investigación</li>
</ul>
<br /><br />
<p>Formato: PDF, Word.</p>
<p>Letra: Arial o Times New Roman</p>
<p>Tamaño: 12</p>
<p>Interlineado: 1.5</p>
