<html>
<head>
	<style type="text/css">
		body{
			font-family: Tahoma, sans-serif;
			font-size: 12px;
		}
	</style>
</head>
<body>
	<p><img src="<?php echo __BASEURL__ ?>/images/logo.jpg"></p>
		<h2 style="text-align: center;">MAESTRÍA EN CIENCIAS SOCIALES<br />
		Facultad de Ciencias Políticas y Sociales<br />
		Universidad Autónoma de Querétaro</h2>
				
		
	
	<h1>Expediente aprobado</h1>
	<p><strong><?php echo $data['nombre']; ?> :</strong></p>
	<p>Le informamos que su expediente ha sido aprobado en su totalidad en la  fecha: <strong><?php echo $data['fecha']; ?></strong>.</p>
	<br /><br />
	
	
	<p>Los aspirantes al curso de selección para el ingreso a la Maestría en Ciencias Sociales, que ofrece la Facultad de Ciencias Políticas y Sociales, deberán presentarse el día 8 de febrero a las 8:45 hrs en las instalaciones de la Facultad ubicada en Centro Universitario s/n Col. Las Campanas, Querétaro, Qro. con la siguiente documentación:</p>
		
		<p>Comprobante de registro en línea<br />
		Identificación oficial (credencial de elector o pasaporte)<br />
		Ejemplar impreso del proyecto de investigación presentado para esta convocatoria<br />
		Pluma negra<br />
		Lápiz No. 2</p>
		
		<br /><br /><br />
		<p style="font-size: 11px">Informes: Coordinación de la Maestría en Ciencias Sociales<br />
		Centro Universitario, Cerro de las Campanas S/N C.P. 76010 Querétaro, Qro.<br />
		Tel. 01 (442) 1921200 Ext. 5453 y 5471<br />
		Página web: http://fcps.uaq.mx/posgrados/maestria_ciencias_sociales/<br />
		Correo: maestria.sociales@uaq.mx</p>

</body>
</html>